# Generated by Django 3.0.4 on 2020-05-08 10:09

import datetime
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('middle_name', models.CharField(blank=True, max_length=250)),
                ('date_of_birth', models.DateField()),
                ('street_address', models.CharField(max_length=250)),
                ('postal_code', models.CharField(max_length=20)),
                ('province', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('phone', phone_field.models.PhoneField(blank=True, max_length=31)),
                ('email', models.EmailField(blank=True, max_length=30)),
            ],
            options={
                'ordering': ('first_name', 'last_name'),
            },
        ),
        migrations.CreateModel(
            name='GivingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giving_date', models.DateField(default=datetime.date.today)),
                ('offering_amount', models.FloatField(blank=True, null=True)),
                ('tithe_amount', models.FloatField(blank=True, null=True)),
                ('building_fund_amount', models.FloatField(blank=True, null=True)),
                ('Other_amount', models.FloatField(blank=True, null=True)),
                ('members', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='members', to='DbEntry.RegistrationModel')),
            ],
            options={
                'ordering': ('-giving_date',),
            },
        ),
    ]
