# Generated by Django 3.0.4 on 2020-06-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('Hospitality Exp', 'Hospitality Exp'), ("Pastor's gift", "Pastor's gift"), ('Welfare Exp', 'Welfare Exp'), ('Other', 'Other')], max_length=200)),
                ('entry_value', models.FloatField()),
            ],
        ),
    ]
