# Generated by Django 3.0.4 on 2020-06-22 00:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_entry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalentry',
            options={'verbose_name_plural': 'Journal Entries'},
        ),
        migrations.AddField(
            model_name='journalentry',
            name='entry_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
