# Generated by Django 3.0.4 on 2020-06-22 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_entry', '0002_auto_20200621_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='short_note',
            field=models.TextField(default='', max_length=300),
        ),
    ]
