# Generated by Django 3.0.4 on 2020-08-11 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_entry', '0003_journalentry_short_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='short_note',
            field=models.TextField(default='', max_length=500),
        ),
    ]
