# Generated by Django 3.0.4 on 2020-09-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tithely_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net_amount', models.FloatField()),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('giving_type', models.CharField(max_length=50)),
                ('trans_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
