# Generated by Django 3.0.4 on 2020-09-28 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tax', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tithely_2',
            new_name='Tithely',
        ),
    ]
